project:
  type: website

website:
  title: "Meta-analysis: Overall Accuracy in Remote Sensing"
  sidebar:
    contents: 
      - href: index.qmd
        text: Home
      - href: khatami_analysis.qmd
        text: Using Khatami's Dataset
      - href: dashboard.qmd
        text: Active Analysis Dashboard
      - href: codebook.qmd
        text: Contribute Data.

format:
  html:
    html-table-processing: none
    theme: minty
    toc: false
    include-in-header: in-line_math_mode.html

execute:
  echo: false
  message: false
  warning: false
  enabled: true
    
bibliography: references.bib
editor: visual

